replicaCount: 2

image:
  repository: ghcr.io/bodkagr/ecommerce-app
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

service:
  type: ClusterIP
  db:
    port: 5432
    targetPort: 5432
  app:
    port: 80
    targetPort: 8080

postgres:
  image: postgres:16-alpine

config:
  DB_HOST: postgres
  DB_NAME: images-gallery
  DB_PORT: "5432"

secret:
  DB_USER: user
  DB_PASSWORD: user123