apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: "{{ .Values.service.db.port }}"
      targetPort: "{{ .Values.service.db.targetPort }}"